service: tubbysea

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 250
  region: eu-central-1
  endpointType: REGIONAL # Set to regional because the api gateway will be behind a cloudfront distribution
  stage: prod
  apiGateway:
    binaryMediaTypes:
      - 'image/png'
      - 'image/jpeg'
  tracing: # Enable X-Ray tracing (debugging)
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow # X-Ray permissions
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource:
        - "Fn::GetAtt": [DynamoTable, Arn]
    - Effect: Allow # Lambda logs on cloudwatch
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "Fn::Join":
            - ":"
            - - "arn:aws:logs"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "log-group:/aws/lambda/*:*:*"
    # For warm-up functions
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:*Object*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - "arn:aws:secretsmanager:eu-central-1:249187628721:secret:oracle-privkey-BgJt7N"
  environment:
    tableName: ${self:custom.tableName}
    stage: ${self:custom.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude:
        - ethers
        - sharp
    packager: "npm"
    excludeFiles: src/**/*.test.ts
  prune:
    automatic: true
    number: 5 # Number of versions to keep
  tableName: prod-table
  domainMap:
    prod:
      domain: api.tubbysea.com
      certificateArn: "arn:aws:acm:us-east-1:249187628721:certificate/f8230c4f-7cf4-49c5-90d0-e5c49bcef4b6"
      hostedZone: tubbysea.com
  domain: ${self:custom.domainMap.${self:custom.stage}.domain}
  certificateArn: ${self:custom.domainMap.${self:custom.stage}.certificateArn}
  hostedZone: ${self:custom.domainMap.${self:custom.stage}.hostedZone}

functions:
  getQuote:
    handler: src/getQuote.default
    timeout: 120
    memorySize: 2000
    events:
      - http:
          path: quote/tubby
          method: get
  getNftMetadata:
    handler: src/getNftMetadata.default
    timeout: 120
    memorySize: 2000
    events:
      - http:
          path: nft/ethereum/{nftContract}/{nftId}
          method: get
  getNftImage:
    handler: src/getNftImage.default
    timeout: 120
    memorySize: 2000
    events:
      - http:
          path: image/{imageUrl}
          method: get
          response:
            contentHandling: CONVERT_TO_BINARY
  storeFloorPrice:
    handler: src/storeFloorPrice.default
    timeout: 60
    memorySize: 3000
    events:
      - schedule: cron(0 * * * ? *)

resources:
  # CORS for api gateway errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # Cloudfront API distribution
  - ${file(resources/api-cloudfront-distribution.yml)}

plugins:
  - serverless-webpack-fixed
  - serverless-offline
  - serverless-prune-plugin
